#version: "3.8"

x-environment-base: &env-base
  OLLAMA_HOST: http://host.docker.internal:11434
  LLM_PROVIDER: ollama
  OLLAMA_MODEL: gpt-oss:20b
  CODEX_PORT: "1455"
  TERM: ${TERM}

services:
  c0-dev:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxy-net
    ports:
      - 127.0.0.1:1455:1455
      - 3000:3000
    working_dir: /home/dev
    tty: true
    environment:
      <<: *env-base
      http_proxy: http://aegis-proxy:9090
      HTTP_PROXY: http://aegis-proxy:9090
      https_proxy: http://aegis-proxy:9090
      HTTPS_PROXY: http://aegis-proxy:9090
    entrypoint:
      - /usr/local/bin/docker-entrypoint.sh
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  proxy-net:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.30.0.0/16

