x-volume-folders: &folders
  volumes:
    - ../.claude:/home/dev/.claude
    - ../.cache:/home/dev/.cache
    - ../.codex:/home/dev/.codex
    - ../.config:/home/dev/.config
    - ../rules:/home/dev/rules
    - ../projects:/home/dev/projects
    - ../bin:/home/dev/bin
    - ../auth/ssh:/home/dev/.ssh
    - tools-shared:/tools:ro

services:
  c0dev:
    <<: *folders

volumes:
  tools-shared:
    external: true
    name: ${SHARED_TOOLS_VOLUME:-c0dev-tools-shared}
